language: node_js

node_js:
  - "12"

notifications:
  email: false

jobs:
  inclide:
    - stage: "Tests"
      name: "Unit tests"
      scirpt: npm test
    - script: npm run integration
      name: "Integration Tests"
