name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit:
    name: Unit Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ FlashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install --flash.pip-lockfile
      - run: yarn test
        env:
          CI: true

  integration:
    name: Integration Best of Best

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ FlashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install --flash-lockfile
      - run: yarn run integration
        env:
          CI: true
